server:
  port: 9200
  servlet:
    context-path: /cyberpay-gateway

spring:
  profiles:
    active: dev
  jmx:
    default-domain: cyberpay-gateway
  config:
    import:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
